# Generated by Django 2.1.4 on 2018-12-30 00:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_url', models.URLField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('es_id', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='api.Article')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
