# Generated by Django 2.1.5 on 2019-01-31 02:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='words',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
