# Generated by Django 2.1.5 on 2019-01-31 02:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190131_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='words',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
