# Generated by Django 2.1.5 on 2019-02-02 22:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190131_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='content',
        ),
        migrations.AddField(
            model_name='sentence',
            name='category',
            field=models.CharField(default='sentence', max_length=100),
        ),
        migrations.AddField(
            model_name='sentence',
            name='elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), default=list, size=None),
        ),
        migrations.AddField(
            model_name='sentence',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
    ]
