# Generated by Django 2.1.5 on 2019-02-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190202_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='words',
        ),
    ]
