# Generated by Django 2.1.5 on 2019-02-02 23:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190202_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='elements',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
