# Generated by Django 2.2.3 on 2019-07-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190202_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('restriction', models.CharField(default='', max_length=100)),
                ('xref', models.CharField(default='', max_length=100)),
                ('antonym', models.CharField(default='', max_length=100)),
                ('pos', models.CharField(default='', max_length=100)),
                ('field', models.CharField(default='', max_length=100)),
                ('misc', models.CharField(default='', max_length=100)),
                ('source_lang', models.CharField(default='', max_length=100)),
                ('source_word', models.CharField(default='', max_length=100)),
                ('sense_information', models.CharField(default='', max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.CharField(default='', max_length=1000)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sense')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('category', models.CharField(default='', max_length=100)),
                ('characters', models.CharField(default='', max_length=100)),
                ('information', models.CharField(default='', max_length=100)),
                ('priority', models.CharField(default='', max_length=100)),
                ('restriction', models.CharField(default='', max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
