# Generated by Django 2.2.3 on 2019-07-16 23:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20190715_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='freq_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interval', models.IntegerField()),
                ('method', models.CharField(default='', max_length=500)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
        ),
    ]
