# Generated by Django 2.2.3 on 2019-07-17 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20190717_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='timestamp',
            new_name='last_seen',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='sentence',
            new_name='sentences',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='method',
        ),
        migrations.AddField(
            model_name='sentence',
            name='viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
